<?php
session_start();
date_default_timezone_set('Asia/Manila');

if (!isset($_SESSION['user_id']) || $_SESSION['role'] != 'admin') {
    die("Unauthorized access");
}

require_once '../vendor/autoload.php';
require_once '../config/database.php';
use Dompdf\Dompdf;
use Dompdf\Options;

$database = new Database();
$db = $database->getConnection();

function getBase64Image($path) {
    if (file_exists($path)) {
        $type = pathinfo($path, PATHINFO_EXTENSION);
        $data = file_get_contents($path);
        return 'data:image/' . $type . ';base64,' . base64_encode($data);
    }
    return '';
}

$uccLogo = getBase64Image('../assets/UCC_Logo.png');
$caloocanLogo = getBase64Image('../assets/caloocan.png');

$id = $_GET['id'] ?? 0;

$stmt = $db->prepare("SELECT th.*, u.full_name as processor_name FROM transfer_history th 
                      LEFT JOIN users u ON th.transferred_by = u.id WHERE th.id = ?");
$stmt->execute([$id]);
$data = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$data) die("Record not found.");

// FETCH ALL ITEMS IN THIS BATCH
$id_list = explode(',', $data['equipment_ids']);
$table_map = [
    'computer' => 'computer_inventory', 
    'computer_lab' => 'computer_inventory', // Added this
    'kitchen' => 'kitchen_equipment', 
    'office' => 'office_equipment', 
    'lab' => 'lab_equipment',
    'regular_lab' => 'lab_equipment', // Added this
    'general' => 'general_equipment'
];
$target_table = $table_map[$data['equipment_type']] ?? 'general_equipment';

$placeholders = implode(',', array_fill(0, count($id_list), '?'));
$item_stmt = $db->prepare("SELECT * FROM $target_table WHERE id IN ($placeholders)");
$item_stmt->execute($id_list);
$items = $item_stmt->fetchAll(PDO::FETCH_ASSOC);

$html = '
<html>
<head>
    <style>
        @page { margin: 100px 25px; }
        body { font-family: "Helvetica", sans-serif; font-size: 11px; color: #333; line-height: 1.4; }
        
        .header { position: fixed; top: -85px; left: 0px; right: 0px; height: 100px; }
        .header table { width: auto; margin: 0 auto; border-collapse: collapse; }
        .header .logo-ucc { padding-right: 15px; }
        .header .header-text { text-align: center; }
        .header h1 { margin: 0; font-size: 18px; color: #000; letter-spacing: 1px; }
        .report-title { margin-top: 5px; font-weight: bold; text-decoration: underline; font-size: 12px; text-transform: uppercase; }

        .footer { position: fixed; bottom: -60px; left: 0px; right: 0px; height: 60px; border-top: 1px solid #ccc; padding-top: 10px; }
        .footer table { width: 100%; border-collapse: collapse; }
        .logo-caloocan img { width: 130px; }

        .summary-section { margin-top: 20px; border: 1px solid #ddd; padding: 10px; background: #f9f9f9; }
        .summary-table { width: 100%; }
        .label { font-weight: bold; width: 25%; }

        .items-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        .items-table th { background: #333; color: #fff; padding: 8px; text-align: left; text-transform: uppercase; font-size: 10px; border: 1px solid #333; }
        .items-table td { padding: 8px; border: 1px solid #ddd; vertical-align: top; }
        
        .signature-section { margin-top: 50px; width: 100%; }
        .sig-box { border-top: 1.5px solid #000; text-align: center; width: 220px; margin-top: 40px; }
        .sig-container { display: inline-block; width: 45%; vertical-align: top; }
    </style>
</head>
<body>
    <div class="header">
        <table>
            <tr>
                <td class="logo-ucc">' . ($uccLogo ? '<img src="' . $uccLogo . '" style="width: 55px;">' : '') . '</td>
                <td class="header-text">
                    <h1>UNIVERSITY OF CALOOCAN CITY</h1>
                    <p style="margin:0;">INVENTORY MANAGEMENT SYSTEM</p>
                    <p class="report-title">Official Inventory Transfer Slip</p>
                </td>
            </tr>
        </table>
    </div>

    <div class="footer">
        <table width="100%">
            <tr>
                <td width="33%">Generated by: <strong>' . htmlspecialchars($_SESSION['full_name'] ?? 'Admin') . '</strong></td>
                <td width="34%" align="center">Batch ID: #TRNS-' . str_pad($data['id'], 5, "0", STR_PAD_LEFT) . '</td>
                <td width="33%" align="right">
                    <div class="logo-caloocan">' . ($caloocanLogo ? '<img src="' . $caloocanLogo . '">' : '') . '</div>
                </td>
            </tr>
        </table>
    </div>

    <div class="summary-section">
        <table class="summary-table">
            <tr>
                <td class="label">Date:</td><td>' . date("F d, Y - h:i A", strtotime($data['transfer_date'])) . '</td>
                <td class="label">From Campus:</td><td style="color: #d32f2f;">' . htmlspecialchars($data['from_campus']) . '</td>
            </tr>
            <tr>
                <td class="label">Total Items:</td><td>' . count($items) . '</td>
                <td class="label">To Campus:</td><td style="color: #2e7d32; font-weight: bold;">' . htmlspecialchars($data['to_campus']) . '</td>
            </tr>
        </table>
    </div>

        <table class="items-table">
        <thead>
            <tr>
                <th width="10%">Item No.</th>
                <th width="12%">Article</th> 
                <th width="18%">Description</th>
                <th width="15%">Property No.</th>
                <th width="15%">Serial Info</th>
                <th width="15%">Previous Accountable Person</th> <!-- Changed from Campus -->
                <th width="15%">New Accountable Person</th> <!-- Changed from Accountable Person -->
            </tr>
        </thead>
        <tbody>';

        foreach ($items as $item) {
            // Mapping Description based on item type
            $desc = $item['computer_set_description'] ?? $item['equipment_name'] ?? '---';
            
            // Mapping Article
            $article = htmlspecialchars($item['article'] ?: '---');

            // FIXED: Property Number - use the actual property_no column
            $propNo = !empty($item['property_no']) ? htmlspecialchars($item['property_no']) : 'N/A';

            // Logic for Serial Info Column - now using serial_number_monitor and serial_number_system for computers
            $serialInfo = "";
            if (!empty($item['serial_number_monitor']) || !empty($item['serial_number_system'])) {
                $serialInfo = "<small style='font-size: 8px;'>";
                $serialInfo .= "MON: " . htmlspecialchars($item['serial_number_monitor'] ?: 'N/A') . "<br>";
                $serialInfo .= "SYS: " . htmlspecialchars($item['serial_number_system'] ?: 'N/A');
                $serialInfo .= "</small>";
            } else {
                $serialInfo = htmlspecialchars($item['serial_number'] ?: 'N/A');
            }

            $html .= '<tr>
                <td style="font-family: monospace;">' . htmlspecialchars($item['item_number'] ?? 'N/A') . '</td>
                <td>' . $article . '</td> 
                <td><strong>' . htmlspecialchars($desc) . '</strong></td>
                <td>' . $propNo . '</td> <!-- FIXED: Now shows property_no, not serial_number -->
                <td>' . $serialInfo . '</td>
                <td>
                    <span style="color: #666;">' . htmlspecialchars($data['previous_accountable'] ?? 'N/A') . '</span> <!-- Previous Accountable -->
                </td>
                <td>
                    <span style="color: #2e7d32; font-weight: bold;">' . htmlspecialchars($data['new_accountable']) . '</span> <!-- New Accountable -->
                </td>
            </tr>';
        }

$html .= '
        </tbody>
    </table>

    <div style="margin-top: 30px;">
        <p>This document serves as an official acknowledgment that the physical custody and accountability of the <strong>' . count($items) . '</strong> items listed above have been transferred.</p>
    </div>

    <div class="signature-section">
        <div class="sig-container">
            <div style="height: 40px;"></div>
            <div class="sig-box">
                <strong>' . htmlspecialchars($data['new_accountable']) . '</strong><br>
                <small>Receiver Signature / Name</small>
            </div>
        </div>
        <div class="sig-container" style="float: right;">
            <div style="height: 40px;"></div>
            <div class="sig-box">
                <strong>' . htmlspecialchars($data['previous_accountable'] ?? 'N/A') . '</strong><br>
                <small>Transferor / Previous Accountable Person</small> <!-- Changed title -->
            </div>
        </div>
    </div>
</body>
</html>';

$options = new Options();
$options->set('isHtml5ParserEnabled', true);
$options->set('isRemoteEnabled', true); 
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

$dompdf->stream("Transfer_Report_Batch_" . $data['id'] . ".pdf", ["Attachment" => false]);
?>